GG = c++
SRC = main.cpp PhoneBook.cpp Contact.cpp
CPPFLAGS = -Wall -Wextra -Werror -std=c++98
NAME = phonebook

all: $(NAME)

$(NAME) : $(SRC)
	$(GG) $(CPPFLAGS) $(SRC) -o $(NAME)

fclean:
	rm -rf $(NAME)